### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by vanesyan** [fundamentals/fundamentals#1]
***The kinda of things to be done, before public beta.1:***
* [ ] **Components**
  * [x] `.page`
  * [ ] `.grid`
  * [ ] `.overlay`
  * [ ] `.button`
  * [x] `.buttonGroup`
  * [x] `.fieldGroup` (*decide on name*)
  * [ ] `.textField` (*decide on name*)
  * [x] `.flexEmbed`
  * [ ] `.popover`

* [ ] **Base**
  * [ ] **types**

* [ ] **Utilities**
  * [ ] `u-width*`
  * [ ] `u-overflow*`
  * [ ] `u-text*`

* [ ] **Automation (CI, etc.)** (***travis-ci***, ***saucelabs***)
* [ ] **Documentation**
  * [ ] **README.md**
    * [ ] **How to**
    * [ ] **License**
  * [ ] **CONTRIBUTING.md** - contributing guide
* [ ] **Web Site**
  * [ ] **Front-end**

*The list would be updated, as We move toward*
